In [1]:
import numpy as np

In [2]:
array_1=np.array([1,2,3,4,5,5])

In [3]:
array_1

array([1, 2, 3, 4, 5, 5])

In [4]:
array_2=np.array([2,3,4,5,6,6])

In [5]:
array_1+array_2

array([ 3,  5,  7,  9, 11, 11])

In [6]:
array_1.dtype

dtype('int32')

In [7]:
array_1.size

6

In [8]:
array_1.shape

(6,)

In [14]:
array_3=np.arange(1,10,3)

In [15]:
array_3

array([1, 4, 7])

In [17]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [22]:
a=np.random.randint(10,size=20).reshape(4,5)

In [23]:
a

array([[0, 9, 1, 9, 9],
       [4, 8, 2, 9, 4],
       [2, 0, 6, 3, 9],
       [3, 0, 8, 7, 7]])

In [24]:
b=np.random.randint(10,size=20).reshape(4,5)

In [25]:
a+b

array([[ 6, 18,  1, 16, 14],
       [ 8, 11,  4, 11, 11],
       [ 9,  8,  7, 12, 12],
       [ 3,  0,  8, 12, 10]])

In [26]:
b.T

array([[6, 4, 7, 0],
       [9, 3, 8, 0],
       [0, 2, 1, 0],
       [7, 2, 9, 5],
       [5, 7, 3, 3]])

In [27]:
b=b.T

In [30]:
a

array([[0, 9, 1, 9, 9],
       [4, 8, 2, 9, 4],
       [2, 0, 6, 3, 9],
       [3, 0, 8, 7, 7]])

In [31]:
b

array([[6, 4, 7, 0],
       [9, 3, 8, 0],
       [0, 2, 1, 0],
       [7, 2, 9, 5],
       [5, 7, 3, 3]])

In [32]:
a.dot(b)

array([[189, 110, 181,  72],
       [179,  90, 187,  57],
       [ 78,  89,  74,  42],
       [102,  91, 113,  56]])

In [33]:
a*b.T

array([[ 0, 81,  0, 63, 45],
       [16, 24,  4, 18, 28],
       [14,  0,  6, 27, 27],
       [ 0,  0,  0, 35, 21]])